### ISSUE TITLE
Crashing on Pie

### ISSUE THREAD

**Issue by TacoTheDank** [pmarks-net/chromadoze#22]
```
FATAL EXCEPTION: main
Process: net.pmarks.chromadoze, PID: 17805
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d09eb7d u0 net.pmarks.chromadoze/.NoiseService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1855)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6990)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by pmarks-net** [comment]
The service should be calling `startForeground()` here:
https://github.com/pmarks-net/chromadoze/blob/master/app/src/main/java/net/pmarks/chromadoze/NoiseService.java#L103

Google Play Console shows this affecting a total of 3 users in the last 60 days.  What device did you see this on, and was anything unusual happening at the time?

**Comment by TacoTheDank** [comment]
I guess the only unusual thing happening were the crashes.

I have a Samsung Note 9, running Android Pie.

**Comment by pmarks-net** [comment]
Does it crash every time, or just at random?

**Comment by TacoTheDank** [comment]
Yeah, I think it happened every time
